class MCPDisplayServerConfig:
    # Monitor type configuration
    LAPTOP_MONITOR = True

    # Desktop monitor positions
    DESKTOP_MONITOR_CANVAS_X_POS = 452
    DESKTOP_MONITOR_CANVAS_Y_POS = 277
    DESKTOP_MONITOR_TOOLBAR_RECTANGLE_X_POS = 532
    DESKTOP_MONITOR_TOOLBAR_RECTANGLE_Y_POS = 82

    # Laptop monitor positions
    LAPTOP_MONITOR_CANVAS_X_POS = 740
    LAPTOP_MONITOR_CANVAS_Y_POS = 589
    LAPTOP_MONITOR_TOOLBAR_RECTANGLE_X_POS = 805
    LAPTOP_MONITOR_TOOLBAR_RECTANGLE_Y_POS = 130

    # Canvas dimensions
    PAINT_CANVAS_WIDTH = 1030
    PAINT_CANVAS_HEIGHT = 632

    # Monitor resolutions (commented out for now)
    # DESKTOP_MONITOR_RESOLUTION = (1920, 1080)
    # LAPTOP_MONITOR_RESOLUTION = (2496, 1664)